### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dabeefer** [Swag1400/discord-bot#4]
how the fuck do i use this shit bruh, you gotta leave instructions or sum

**Comment by chxei** [comment]
> how the fuck do i use this shit bruh, you gotta leave instructions or sum

This is github dude, here we host code. You should first learn to code. Don't expect author to learn you how java or some programming language works. And don't be rude simply because you can't understand shit. That's your problem. Everything is self explanatory here.

**Comment by dabeefer** [comment]
> > how the fuck do i use this shit bruh, you gotta leave instructions or sum
> 
> This is github dude, here we host code. You should first learn to code. Don't expect author to learn you how java or some programming language works. And don't be rude simply because you can't understand shit. That's your problem. Everything is self explanatory here.

my bad man, i was trying to come off rude, i was just genuinley asking and didnt think about my speech.

**Comment by dabeefer** [comment]
but anyways i get the error ' Error: Could not find or load main class me.comu.exeter.core.Core', when i try to run the bot in intelij idea so if someone could help i would appreciate it.

**Comment by insurancefraud** [comment]
> but anyways i get the error ' Error: Could not find or load main class me.comu.exeter.core.Core', when i try to run the bot in intelij idea so if someone could help i would appreciate it.

build gradle then run core

**Comment by lxi1400** [comment]
> but anyways i get the error ' Error: Could not find or load main class me.comu.exeter.core.Core', when i try to run the bot in intelij idea so if someone could help i would appreciate it.

Make a .env file and insert

TOKEN=BOTTOKEN
OWNER=YOUID
GUI=FALSE
